[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "'NONCE_KEY', '.*'",
]

[default.extend-identifiers]
# Typos
"Github" = "GitHub"
"Wordpress" = "WordPress"

[default.extend-words]
# Don't correct the surname "Teh"
Encrypter = "Encryptor"
Encryptor = "Encrypter"
