[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "'NONCE_KEY', '.*'",
]

[default.extend-identifiers]
# Typos
"Encrypter" = "Encryptor"
"Github" = "GitHub"
"Wordpress" = "WordPress"
