services:

  mysql:
    image: mysql:8.4
    command: --mysql-native-password=ON
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wordpress_test"
