name: Check for typos

permissions:
  contents: read

on:
  pull_request:

env:
  CLICOLOR: 1

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: files
        uses: masesgroup/retrieve-changed-files@v3

      - name: Run typos
        uses: crate-ci/typos@v1.32.0
        with:
          files: ${{ steps.files.outputs.files }}
